package mitto.sms.service;

import mitto.sms.hibernate.dao.StatsDTO;
import mitto.sms.hibernate.entity.CountryFee;
import mitto.sms.hibernate.entity.Entity;

import java.util.List;

/**
 * An Object implemented SmsService interface providing operation and logic for handling sms data request
 */
public interface SmsService {

    /**
     * Setting CountryFeeEnabled true enables using extra information stored in CountryFee entity
     * and changing logic for preparing formatted outputs,
     * @param enabled if true - extending top senders with total price
     */
    void setCountryFeeEnabled(boolean enabled);

    /**
     * Handle persisting entity
     * @param entity entity to store
     * @return true if save finish successfully and entity is stored
     * @see CountryFee
     */
    boolean saveEntity(Entity entity);

    /**
     * providing list of formatted top senders (limited and ordered), every item in list is generated by format base on countryFeeEnabled
     * if countryFeeEnabled is False format:
     * [sender][space][total count of messages]
     * if countryFeeEnabled is True format:
     * [sender][space][total count of messages][space][total sum of messages price]
     * @param limit of senders
     * @return list of formatted sender results
     */
    List<StatsDTO> getTopSendersStats(Integer limit);

    /**
     * providing list of formatted country (ordered), every item in list is generated by format:
     * [country][space][total count of messages][space][total sum of messages price]
     * @return list of formatted country fee results
     */
    List<StatsDTO> getCountryFeeStats();
}
